### ISSUE TITLE
Ability to set defaults for player

### ISSUE THREAD

**Issue by neilotoole** [cljoly/gohugo-asciinema#6]
I always want the same asciiplayer theme. For example, in`params.toml`:

```toml
[asciinema]
  [asciinema.defaults]
    theme = "solarized-dark"
    loop = true
    autoPlay = true
    speed = "2.5"
```
